### PR TITLE
Cookie issues

### LINKED ISSUE #391: CookieMiddleware Incorrect separation of cookies in Cookie header
Correct separation of multiple cookies in Cookie header is `;`, but `,` is used instead.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cookie#Syntax

Incorrect assert in test:
https://github.com/kriswallsmith/Buzz/blob/master/tests/Unit/Middleware/Cookie/CookieJarTest.php#L60

### LINKED ISSUE #392: CookieMiddleware cookies with existing name are added instead of updated
This results in Cookie header, together with issue #391, to look like this: 
`Cookie: PHPSESSID=37f0tkl68vu8k4bgboqdep3ti2, PHPSESSID=7tmrmb9uebe92rgf6t0fju9a25`

### PR DESCRIPTION
**Pull request by Nyholm**
This will fix #391 and fix #392

### CODE REVIEW

File: lib/Middleware/Cookie/CookieJar.php [hunk 1]
```diff
@@ -84,4 +87,19 @@ public function clearExpiredCookies(): void
...
+     * may have different values.
+     */
+    private function getHash(Cookie $cookie): string
+    {
+        return sha1(sprintf(
+            '%s|%s|%s|%s',
+            $cookie->getName(),
+            $cookie->getAttribute('domain'),
+            $cookie->getAttribute('path'),
+            $cookie->getAttribute('http')
```
Comment (Tetragramat) [inline lib/Middleware/Cookie/CookieJar.php]: I don't think that `http` attribute exists.

Maybe use some constants?
https://github.com/kriswallsmith/Buzz/blob/62422cbbd17efa757353116d42508fda8503c754/lib/Middleware/Cookie/Cookie.php#L11-L19

Comment (Nyholm) [reply lib/Middleware/Cookie/CookieJar.php]: Of course, Excellent idea. 

Thanks!
